// <auto-generated />
using System;
using Maintain_Patient_Info.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maintain_Patient_Info.Migrations
{
    [DbContext(typeof(PatientManagementContext))]
    partial class PatientManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maintain_Patient_Info.Base.Facilites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Facilites");
                });

            modelBuilder.Entity("Maintain_Patient_Info.Base.PatientsRegistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfRegi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PateintId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PatientsRegistory");
                });

            modelBuilder.Entity("Maintain_Patient_Info.HospitalServices.Consultation", b =>
                {
                    b.Property<int>("ConsultationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsultationId");

                    b.ToTable("Consultation");

                    b.HasData(
                        new
                        {
                            ConsultationId = 1,
                            Charge = 4005,
                            Purpose = "skin Problem"
                        },
                        new
                        {
                            ConsultationId = 2,
                            Charge = 500,
                            Purpose = "Cardiac CheckUp"
                        },
                        new
                        {
                            ConsultationId = 3,
                            Charge = 450,
                            Purpose = "Kidney CheckUp"
                        },
                        new
                        {
                            ConsultationId = 4,
                            Charge = 500,
                            Purpose = "Sugar CheckUp"
                        });
                });

            modelBuilder.Entity("Maintain_Patient_Info.HospitalServices.LabTests", b =>
                {
                    b.Property<int>("LabTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.Property<string>("LabTestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabTestResult")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LabTestId");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            LabTestId = 1,
                            Charge = 150,
                            LabTestName = "Blood Test",
                            LabTestResult = "Pending"
                        },
                        new
                        {
                            LabTestId = 2,
                            Charge = 200,
                            LabTestName = "Creatine Test",
                            LabTestResult = "Pending"
                        },
                        new
                        {
                            LabTestId = 3,
                            Charge = 100,
                            LabTestName = "Prick Test",
                            LabTestResult = "Completed"
                        },
                        new
                        {
                            LabTestId = 4,
                            Charge = 150,
                            LabTestName = "Diabetes Test",
                            LabTestResult = "Pending"
                        });
                });

            modelBuilder.Entity("Maintain_Patient_Info.HospitalServices.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("charge")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            RoomType = "Single",
                            charge = 4000
                        },
                        new
                        {
                            RoomId = 2,
                            RoomType = "Single",
                            charge = 4000
                        },
                        new
                        {
                            RoomId = 3,
                            RoomType = "Double",
                            charge = 4000
                        },
                        new
                        {
                            RoomId = 4,
                            RoomType = "ICU",
                            charge = 6000
                        },
                        new
                        {
                            RoomId = 5,
                            RoomType = "Special Rooms",
                            charge = 6500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
